### ISSUE TITLE
在向API发送请求后，返回“429 too request”，对请求进行了限流

### ISSUE THREAD

**Issue by Leo-lu-beep** [Afool4U/MIGPT#11]
Exception in thread Thread-1 (ask_stream):
Traceback (most recent call last):
  File "D:\usual_applications\python\python_interpreter3.10\installation_package\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\usual_applications\python\python_interpreter3.10\installation_package\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\usual_applications\python\Projects\MIGPT\V3.py", line 157, in ask_stream
    raise Exception(
Exception: Error: 429 Too Many Requests {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}
在向API发送请求后，返回“429 too request”，显示超过了使用配额，对请求进行了限流。

**Comment by bt-1120161955** [comment]
我也遇到了这问题，请问你解决了吗

**Comment by Leo-lu-beep** [comment]
> 我也遇到了这问题，请问你解决了吗

看看OpenAI Usage里面的Free trial usage，我的已经过期了，应该是要往账户里充一些钱才能调用API

**Comment by Leo-lu-beep** [comment]
> "message": "You exceeded your current quota, please check your plan and billing details.",

"message": "You exceeded your current quota, please check your plan and billing details.",
