### ISSUE TITLE
一打开就是这样的错误了,另外小爱的网路需要扶墙吗还是只需要脚本运行的服务器扶墙?

### ISSUE THREAD

**Issue by amormason** [Afool4U/MIGPT#17]
<img width="887" alt="image" src="https://github.com/Afool4U/MIGPT/assets/11971043/84c0d150-a5ee-4d56-96e1-118033e5bf1f">

以下是小爱的回答:  我叫小爱，很高兴这次的遇见，我会一直陪伴你的。
Exception in thread Thread-1 (ask_stream):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/fzq/Documents/GitHub/MIGPT/V3.py", line 157, in ask_stream
    raise Exception(
Exception: Error: 429 Too Many Requests {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

**Comment by Afool4U** [comment]
请求过多了，你的api应该是免费版的
