### ISSUE TITLE
报错有问题 账号和密码都没有错

### ISSUE THREAD

**Issue by joe12801** [Afool4U/MIGPT#3]
File "/root/migpt/MIGPT/miaccount.py", line 74, in login
    serviceToken = await self._securityTokenService(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/migpt/MIGPT/miaccount.py", line 114, in _securityTokenService
    async with self.session.get(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api2.mina.mi.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')]
Traceback (most recent call last):
  File "/root/migpt/MIGPT/MIGPT.py", line 304, in <module>
    asyncio.run(miboy.run_forever())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/migpt/MIGPT/MIGPT.py", line 199, in run_forever
    await self.init_all_data(session)
  File "/root/migpt/MIGPT/MIGPT.py", line 92, in init_all_data
    await self._init_data_hardware()
  File "/root/migpt/MIGPT/MIGPT.py", line 116, in _init_data_hardware
    hardware_data = await self.mina_service.device_list()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/migpt/MIGPT/minaservice.py", line 27, in device_list
    result = await self.mina_request("/admin/v2/device_list?master=" + str(master))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/migpt/MIGPT/minaservice.py", line 22, in mina_request
    return await self.account.mi_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/migpt/MIGPT/miaccount.py", line 150, in mi_request
    raise Exception(f"Error {url}: {resp}")
Exception: Error https://api2.mina.mi.com/admin/v2/device_list?master=0&requestId=app_ios_nuB7SxiGTI2KOsPmdYo4yhpAwQ8HjC: Login failed
root@aml:~/migpt/MIGPT#

**Comment by Afool4U** [comment]
这个可能是你本地设置问题？urllib3装指定版本了吗，不能用最新的，然后云服务器也不行

**Comment by CrazyBunQnQ** [comment]
我也遇到了，在 IDE 本地执行的
![image](https://user-images.githubusercontent.com/17765748/226118623-c1c9d442-cf74-4e23-a4a6-945f9f456807.png)

**Comment by CrazyBunQnQ** [comment]
> 我也遇到了，在 IDE 本地执行的 ![image](https://user-images.githubusercontent.com/17765748/226118623-c1c9d442-cf74-4e23-a4a6-945f9f456807.png)

我的问题解决了，去官网登录时发现有验证，过了验证之后，账号就正常了，目测小米检测刀账号有异常之类的

**Comment by jjiikkkk** [comment]
很多人都是账号和密码登录不上去

**Comment by wujunkui** [comment]
先去[小米官网](https://www.mi.com/global/)登录一下，再执行程序就好了。
