### ISSUE TITLE
问了2个问题之后就报错了

### ISSUE THREAD

**Issue by jasontips** [Afool4U/MIGPT#9]
root@debian:/opt/MIGPT# python3 MIGPT.py
正在运行 MiGPT, 请用"打开/关闭高级对话"控制对话模式。
以下是小爱的回答:  答案是二
以下是GPT的回答:  一加一等于二。这是一个非常基本的算术问题，通常在学龄前就已经学会了。在数学中，加法是两个或多个数字的 操作，将它们组合在一起形成一个较大的数字。一加一的答案是二，这是因为每个数字都代表了一个单位，两个单位加在一起就成了两 个单位，也就是数字“2”。
   以下是小爱的回答:  世界有七大洲，分别是亚洲、欧洲、北美洲、南美洲、非洲、大洋洲和南极洲。
以下是GPT的回答:  世界上有七个大洲。大洲是指地球表面上的七个主要陆地区域，包括亚洲、非洲、北美洲、南美洲、欧洲、大洋洲和南极洲。这些大洲都有独特的地理特征、文化、历史和生态系统。亚洲是最大的大洲，面积约为44,579,000平方公里，而南极洲是最小的大洲，面积约为14,000,000平方公里。每个大洲都有自己的特色和价值，对于人类和自然世界都具有重要的意义。
Traceback (most recent call last):
  File "/opt/MIGPT/MIGPT.py", line 305, in <module>
    asyncio.run(miboy.run_forever())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/MIGPT/MIGPT.py", line 274, in run_forever
    while await self.get_if_xiaoai_is_playing() and not \
  File "/opt/MIGPT/MIGPT.py", line 170, in get_if_xiaoai_is_playing
    playing_info = await self.mina_service.player_get_status(self.device_id)
  File "/opt/MIGPT/minaservice.py", line 68, in player_get_status
    return await self.ubus_request(
  File "/opt/MIGPT/minaservice.py", line 32, in ubus_request
    result = await self.mina_request(
  File "/opt/MIGPT/minaservice.py", line 22, in mina_request
    return await self.account.mi_request(
  File "/opt/MIGPT/miaccount.py", line 150, in mi_request
    raise Exception(f"Error {url}: {resp}")
Exception: Error https://api2.mina.mi.com/remote/ubus: {'code': 101, 'message': 'ubus server or device returned invalid result', 'data': {'device_data': '{"msg":"ROM端未响应","code":3012}', 'reqID': 'app_ios_boCEY2gHNRkTQ9tPu5MBmWJwy6DS4O'}}

**Comment by Cstring667** [comment]
我也是

**Comment by wanlin1** [comment]
我也是
